site_name: Saleem's Productivity Tools
site_url: https://saleem.net/productivity-tools/
repo_url: https://github.com/saleemh/productivity-tools
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - tables
  - toc:
      permalink: true
plugins:
  - search
# nav:
#   - Home: index.md
docs_dir: docs
site_dir: site
use_directory_urls: true
